import pandas as pd
import re


# ============================================================
# INDICATOR VALIDATION
# ============================================================

def validate_indicator(value, indicator_type):

    value = str(value).strip()

    if indicator_type == "IP":

        pattern = r"^(?:\d{1,3}\.){3}\d{1,3}$"

        if not re.match(pattern, value):
            return False

        return all(
            0 <= int(part) <= 255
            for part in value.split(".")
        )

    if indicator_type == "Domain":

        return bool(
            re.match(
                r"^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
                value
            )
        )

    if indicator_type == "URL":

        return bool(
            re.match(
                r"^https?://",
                value
            )
        )

    if indicator_type == "SHA-256":

        return bool(
            re.match(
                r"^[a-fA-F0-9]{64}$",
                value
            )
        )

    if indicator_type == "CVE":

        return bool(
            re.match(
                r"^CVE-\d{4}-\d+$",
                value
            )
        )

    return len(value) > 0


# ============================================================
# INDICATOR TESTS
# ============================================================

def test_valid_ip():

    assert validate_indicator(
        "192.0.2.10",
        "IP"
    )


def test_invalid_ip():

    assert not validate_indicator(
        "999.999.999.999",
        "IP"
    )


def test_valid_domain():

    assert validate_indicator(
        "example.com",
        "Domain"
    )


def test_valid_url():

    assert validate_indicator(
        "https://example.com",
        "URL"
    )


def test_invalid_url():

    assert not validate_indicator(
        "example.com",
        "URL"
    )


def test_valid_sha256():

    assert validate_indicator(
        "a" * 64,
        "SHA-256"
    )


def test_invalid_sha256():

    assert not validate_indicator(
        "abcdef",
        "SHA-256"
    )


def test_valid_cve():

    assert validate_indicator(
        "CVE-2026-12345",
        "CVE"
    )


def test_invalid_cve():

    assert not validate_indicator(
        "CVE-ABC",
        "CVE"
    )


# ============================================================
# DATASET TESTS
# ============================================================

def test_dataset_exists():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert len(df) >= 2000


def test_required_columns():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    required_columns = [
        "threat_id",
        "timestamp",
        "threat_name",
        "threat_category",
        "indicator_type",
        "indicator_value",
        "source_name",
        "confidence_score",
        "severity",
        "risk_score",
        "status"
    ]

    for column in required_columns:
        assert column in df.columns


def test_risk_score_range():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert df["risk_score"].between(
        0,
        100
    ).all()


def test_confidence_score_range():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert df["confidence_score"].between(
        0,
        100
    ).all()


def test_threat_ids_unique():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert df["threat_id"].is_unique


def test_severity_values():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    allowed = {
        "Informational",
        "Low",
        "Medium",
        "High",
        "Critical"
    }

    assert set(
        df["severity"].unique()
    ).issubset(allowed)


def test_indicator_types():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    allowed = {
        "IP",
        "Domain",
        "URL",
        "SHA-256",
        "Email/Sender Domain",
        "CVE"
    }

    assert set(
        df["indicator_type"].unique()
    ).issubset(allowed)


def test_status_values():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    # These are the actual statuses generated by generate_data.py
    allowed = {
        "NEW",
        "UNDER_REVIEW",
        "MONITORING",
        "CLOSED",
        "FALSE_POSITIVE"
    }

    assert set(
        df["status"].unique()
    ).issubset(allowed)


# ============================================================
# DATA QUALITY TESTS
# ============================================================

def test_no_empty_threat_ids():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert df["threat_id"].notna().all()


def test_no_empty_indicator_values():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert df["indicator_value"].notna().all()


def test_confidence_numeric():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert pd.api.types.is_numeric_dtype(
        df["confidence_score"]
    )


def test_risk_numeric():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert pd.api.types.is_numeric_dtype(
        df["risk_score"]
    )


def test_dataset_has_multiple_categories():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert df["threat_category"].nunique() >= 5


def test_dataset_has_multiple_indicator_types():

    df = pd.read_csv(
        "data/threat_intelligence_dataset.csv"
    )

    assert df["indicator_type"].nunique() >= 4